"""Remove duplicate profile_photo column

Revision ID: 03d6a3a7cf3a
Revises: 4a02be085b74
Create Date: 2026-07-06 12:49:02.342146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d6a3a7cf3a'
down_revision: Union[str, Sequence[str], None] = '4a02be085b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    op.drop_column('faculty', 'profile_photo_path')
    op.add_column('students', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    op.drop_column('students', 'profile_photo')
    op.drop_column('students', 'profile_photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('profile_photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('students', 'profile_photo_path')
    op.add_column('faculty', sa.Column('profile_photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('faculty', 'profile_photo_path')
    # ### end Alembic commands ###
