"""create student certificates table

Revision ID: 4631527b4c92
Revises: 8c552173a6f6
Create Date: 2026-07-06 16:55:00.509379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4631527b4c92'
down_revision: Union[str, Sequence[str], None] = '8c552173a6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    op.drop_column('faculty', 'profile_photo_path_path')
    op.add_column('student_certificates', sa.Column('issuer', sa.String(length=255), nullable=True))
    op.add_column('student_certificates', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('student_certificates', sa.Column('verification_status', sa.String(length=20), nullable=False))
    op.add_column('student_certificates', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('student_certificates', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_certificates', sa.Column('verification_remarks', sa.Text(), nullable=True))
    op.alter_column('student_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'student_certificates', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_certificates', type_='foreignkey')
    op.alter_column('student_certificates', 'certificate_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('student_certificates', 'verification_remarks')
    op.drop_column('student_certificates', 'verified_at')
    op.drop_column('student_certificates', 'verified_by')
    op.drop_column('student_certificates', 'verification_status')
    op.drop_column('student_certificates', 'issue_date')
    op.drop_column('student_certificates', 'issuer')
    op.add_column('faculty', sa.Column('profile_photo_path_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('faculty', 'profile_photo_path')
    # ### end Alembic commands ###
