"""Add upload fields

Revision ID: 4a02be085b74
Revises: cda888ceb328
Create Date: 2026-07-05 03:14:49.520358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a02be085b74'
down_revision: Union[str, Sequence[str], None] = 'cda888ceb328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_path', sa.String(length=255), nullable=True))
    op.add_column('faculty', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('resume_path', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('profile_photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'profile_photo_path')
    op.drop_column('students', 'resume_path')
    op.drop_column('faculty', 'profile_photo_path')
    op.drop_column('companies', 'logo_path')
    # ### end Alembic commands ###
