"""Add interviews table

Revision ID: 6aba190cb408
Revises: ba0b9daff591
Create Date: 2026-07-03 13:14:35.459748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aba190cb408'
down_revision: Union[str, Sequence[str], None] = 'ba0b9daff591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.Enum('APTITUDE', 'GROUP_DISCUSSION', 'TECHNICAL', 'HR', 'MANAGERIAL', name='interviewtype'), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('interviewer', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'PASSED', 'FAILED', 'ABSENT', name='interviewstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
