"""Add student certificates table

Revision ID: 8c552173a6f6
Revises: 03d6a3a7cf3a
Create Date: 2026-07-06 12:58:26.572807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c552173a6f6'
down_revision: Union[str, Sequence[str], None] = '03d6a3a7cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_certificates',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('certificate_name', sa.String(length=255), nullable=False),
    sa.Column('certificate_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_certificates')
    # ### end Alembic commands ###
