"""Add placement drives table

Revision ID: b3cc83702420
Revises: 3c25ef389066
Create Date: 2026-07-03 12:53:46.384437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cc83702420'
down_revision: Union[str, Sequence[str], None] = '3c25ef389066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_drives',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('job_role', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('package', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('drive_date', sa.Date(), nullable=False),
    sa.Column('registration_deadline', sa.Date(), nullable=False),
    sa.Column('minimum_cgpa', sa.Float(), nullable=False),
    sa.Column('minimum_attendance', sa.Float(), nullable=False),
    sa.Column('backlog_allowed', sa.Boolean(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'COMPLETED', name='drivestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_drives')
    # ### end Alembic commands ###
