"""Add applications table

Revision ID: ba0b9daff591
Revises: b3cc83702420
Create Date: 2026-07-03 13:06:24.426682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0b9daff591'
down_revision: Union[str, Sequence[str], None] = 'b3cc83702420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SHORTLISTED', 'REJECTED', 'SELECTED', name='applicationstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
